<?xml version="1.0" encoding="utf-8"?><Database Name="QLNHANSU" Class="QLNSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-VSQTOGR\SQLEXPRESS;Initial Catalog=QLNHANSU;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QLNHANSUConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChamCong" Member="ChamCongs">
    <Type Name="ChamCong">
      <Column Name="MaChamCong" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Taikhoan_ChamCong" Member="Taikhoan" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="Taikhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Luong" Member="Luongs">
    <Type Name="Luong">
      <Column Name="MaLuong" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="thang" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="nam" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Songaylam" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="tongluong" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="Taikhoan_Luong" Member="Taikhoan" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="Taikhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaPB" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_Taikhoan" Member="Taikhoans" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="Taikhoan" />
      <Association Name="PhongBan_NhanVien" Member="PhongBan" ThisKey="MaPB" OtherKey="MaPB" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhongBan" Member="PhongBans">
    <Type Name="PhongBan">
      <Column Name="MaPB" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPB" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="PhongBan_NhanVien" Member="NhanViens" ThisKey="MaPB" OtherKey="MaPB" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.Taikhoan" Member="Taikhoans">
    <Type Name="Taikhoan">
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenQuyenHan" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Taikhoan_ChamCong" Member="ChamCongs" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="ChamCong" />
      <Association Name="Taikhoan_Luong" Member="Luongs" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="Luong" />
      <Association Name="NhanVien_Taikhoan" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>